import = [
  "~/.cache/wal/colors-alacritty.toml"
  # "~/.config/alacritty/themes/rose-pine.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 30

decorations = "transparent"

opacity = 0.9
# blur = true

option_as_alt = "Both"

[font]
normal.family = "FantasqueSansM Nerd Font"
size = 18
