export PATH=$PATH:~/.spoof-dpi/bin:~/pickup/target/release:~/Library/Python/3.10/lib/python/site-packages:/Users/nikko/.local/bin:/usr/local/bin:/opt/homebrew/opt/postgresql@12/bin:/Applications/Docker.app/Contents/Resources/bin/
export ZLE_RPROMPT_INDENT=1
export HOMEBREW_AUTO_UPDATE_SECS=10224480
export EDITOR="nvim"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export BAT_THEME="base16"
export ATAC_KEY_BINDINGS=~/.config/atac/key_bindings.toml
export FZF_DEFAULT_OPTS="--color fg:8"
