#!/bin/bash
source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/constants.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="MesloLGS Nerd Font"
ICON_FONT="SF Pro"

sketchybar --hotload true

bar=(
  color="$BACKGROUND"
  position=top
  height=40
  padding_right=15
  padding_left=15
  display=all
  sticky=on
  blur_radius=10
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=2
  padding_right=2
  icon.font="$ICON_FONT:Regular:16.0"
  icon.color="$ACCENT"
  icon.padding_left=10
  icon.padding_right=2
  label.font="$FONT:Regular:14:0"
  label.color="$FOREGROUND"
  label.padding_left=10
  label.padding_right=10
  background.color="$BACKGROUND2"
  background.height=30
  background.border_width=2
  background.corner_radius=10
  popup.background.color="$BACKGROUND"
  popup.background.border_color="$ACCENT"
  popup.background.corner_radius=10
)

# bracket=(
#   background.color="$BACKGROUND2"
#   background.corner_radius=10
#   background.height=30
#   background.drawing=on
# )

sketchybar --default "${default[@]}"

##### LEFT ITEMS #####

source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/mic.sh"

##### CENTER ITEMS #####

source "$ITEM_DIR/spaces.sh"

##### RIGHT ITEMS #####

source "$ITEM_DIR/datetime.sh"

sketchybar --add item layout right \
           --set layout icon=󰗊 script="$PLUGIN_DIR/layout.sh" \
           --add event layout_change "AppleSelectedInputSourcesChangedNotification" \
           --subscribe layout layout_change

source "$ITEM_DIR/volume.sh"

sketchybar --add item battery right \
           --set battery icon.padding_left=10 update_freq=60 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

source "$ITEM_DIR/spotify.sh"

sketchybar --update
