#!/bin/bash
source "$HOME/.config/sketchybar/colors.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="FantasqueSansM Nerd Font"

bar=(
  color=$BACKGROUND
  position=top
  height=35
  margin=10
  y_offset=5
  corner_radius=10
  blur_radius=20
  padding_right=10
  padding_left=10
  display=all
  sticky=on
  shadow=on
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Bold:17.0"
  label.font="$FONT:Bold:16:0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=5
  icon.padding_right=5
  label.padding_left=5
  label.padding_right=5
  background.color=$BACKGROUND2
  background.height=25
  background.corner_radius=5
)

sketchybar --default "${default[@]}"

source "$ITEM_DIR/spaces.sh"

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \

sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \

sketchybar --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \

sketchybar --add item vpn right \
           --set vpn update_freq=5 icon=󰖂  script="$PLUGIN_DIR/vpn.sh"

sketchybar --update
