#!/bin/bash
source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/constants.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="JetBrainsMono Nerd Font"
ICON_FONT="SF Pro"

sketchybar --hotload true

bar=(
  color="$TRANSPARENT"
  position=top
  height=30
  margin=5
  y_offset=5
  padding_right=10
  padding_left=10
  display=all
  sticky=on
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="$ICON_FONT:Regular:16.0"
  icon.color="$ACCENT"
  icon.padding_left=2
  icon.padding_right=2
  label.font="$FONT:Regular:14:0"
  label.color="$FOREGROUND"
  label.padding_left=10
  label.padding_right=10
  background.color="$TRANSPARENT"
  background.height=30
  background.border_width=2
  background.corner_radius=15
  popup.background.color="$BACKGROUND"
  popup.background.border_color="$ACCENT"
  popup.background.corner_radius=10
)

bracket=(
  background.color="$BACKGROUND"
  background.corner_radius=10
  background.height=30
  background.drawing=on
)

sketchybar --default "${default[@]}"

##### LEFT ITEMS #####

sketchybar --add item spacer left                \
           --set spacer background.drawing=off   \
                                   width=10      \

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/mic.sh"

sketchybar --add bracket left_bracket spacer spaces weather mic \
           --set         left_bracket "${bracket[@]}"

##### CENTER ITEMS #####

source "$ITEM_DIR/spotify.sh"

sketchybar --add bracket center_bracket spotify \
           --set         center_bracket "${bracket[@]}"

##### RIGHT ITEMS #####

source "$ITEM_DIR/datetime.sh"

sketchybar --add item layout right \
           --set layout icon=󰗊 icon.padding_left=3 script="$PLUGIN_DIR/layout.sh" \
           --add event layout_change "AppleSelectedInputSourcesChangedNotification" \
           --subscribe layout layout_change

source "$ITEM_DIR/volume.sh"

sketchybar --add item battery right \
           --set battery update_freq=60 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

# sketchybar --add item vpn right \
#            --set vpn update_freq=5 label.drawing=off icon=󰖂 icon.font="$FONT:Regular:17.0" icon.padding_right=3 script="$PLUGIN_DIR/vpn.sh" \
#            --subscribe vpn mouse.clicked

source "$ITEM_DIR/spoofdpi.sh"

sketchybar --add bracket right_bracket date layout volume battery vpn spoofdpi \
           --set         right_bracket "${bracket[@]}"

sketchybar --update
