[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
wal-gen = [
    { run = "wal-gen -i $0", desc = "Set wallpaper", for = "unix" }
]

[open]
prepend_rules = [
    { name = "*.png", use = [ "wal-gen" ] },
    { name = "*.jpg", use = [ "wal-gen" ] },
    { name = "*.jpeg", use = [ "wal-gen" ] },
]

[preview]
max_width = 1000
max_height = 1000

[tasks]
image_bound = [ 10000, 10000 ]
