[config]

[templates.wal]
input_path = "~/Library/Application Support/com.InioX.matugen/wal/template.json"
output_path = "~/.config/wal/colorschemes/dark/matugen.json"

[templates.sketchybar]
input_path = "~/Library/Application Support/com.InioX.matugen/sketchybar/template.sh"
output_path = "~/.config/sketchybar/colors.sh"

[templates.discord]
input_path = "~/Library/Application Support/com.InioX.matugen/discord/template.css"
output_path = "~/Library/Application Support/Vencord/settings/quickCss.css"
