[config]

[templates.sketchybar]
input_path = "~/.config/sketchybar/themes/matugen-template.lua"
output_path = "~/.config/sketchybar/themes/matugen.lua"

[templates.ghostty]
input_path = "~/.config/ghostty/themes/matugen-template"
output_path = "~/.config/ghostty/themes/matugen"

[templates.nvim]
input_path = "~/.config/nvim/lua/colorscheme/matugen-template.lua"
output_path = "~/.config/nvim/lua/colorscheme/matugen.lua"
