require("items.clock")
require("items.separator")("left")
require("items.date")
require("items.separator")("left")
require("items.spaces")

require("items.airpods")
require("items.battery")
require("items.kblayout")
require("items.separator")("right")
require("items.music")
