#!/bin/bash

source "$HOME/.config/sketchybar/theme.sh"
source "$HOME/.config/sketchybar/constants.sh"

sketchybar --hotload true

bar=(
    position=left
    y_offset=11
    height=50

    margin=10
    padding_right=20
    padding_left=20

    color="$BACKGROUND_COLOR"
    blur_radius=10
    
    border_color="$BORDER_COLOR"
    border_width=1
    corner_radius=15
    shadow=on

    display=all
    sticky=on
    topmost=off
    font_smoothing=on
)

sketchybar --bar "${bar[@]}"

default=(
    width=25

    icon.font="$ICON_FONT"
    icon.font.style="Regular"
    icon.font.size=14
    icon.color="$ICON_COLOR"

    label.font="$FONT"
    label.font.style="Regular"
    label.font.size=14

    label.color="$TEXT_COLOR"
    label.y_offset=0

    popup.background.color="$BACKGROUND_COLOR"
    popup.background.border_color="$BORDER_COLOR"
    popup.background.border_width=1
    popup.background.corner_radius=10
    popup.background.shadow.drawing=on
    popup.y_offset=5
)

sketchybar --default "${default[@]}"

##### LEFT (TOP) ITEMS #####

source "$HOME/.config/sketchybar/items/front_app.sh"
source "$HOME/.config/sketchybar/items/weather.sh"
source "$HOME/.config/sketchybar/items/airpods.sh"
source "$HOME/.config/sketchybar/items/telegram.sh"
source "$HOME/.config/sketchybar/items/discord.sh"
source "$HOME/.config/sketchybar/items/spaces.sh"

##### CENTER ITEMS #####

source "$HOME/.config/sketchybar/items/apple_music.sh"
# source "$HOME/.config/sketchybar/items/spotify.sh"

##### RIGHT ITEMS #####

source "$HOME/.config/sketchybar/items/datetime.sh"
source "$HOME/.config/sketchybar/items/layout.sh"
source "$HOME/.config/sketchybar/items/volume.sh"
source "$HOME/.config/sketchybar/items/battery.sh"
source "$HOME/.config/sketchybar/items/vpn.sh"

sketchybar --update
# sketchybar --animate sin 20 --bar y_offset=5 y_offset=0
